spring:
  application:
    name: lovable-clone   # Name of your Spring Boot application


  datasource:
    url: jdbc:postgresql://localhost:9010/pgvector-test  # PostgreSQL DB URL (Docker port
    username: user   # DB username
    password: password     # DB password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update      # Auto-create/update tables based on entities
    show-sql: true          # Print SQL queries in console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect   # Hibernate dialect for PostgreSQL
        format_sql: true    # Pretty-print SQL output (NOTE: Correct spelling is format_sql)

  ai:
    openai:
      api-key: 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
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: qwen/qwen3-coder:free
          temperature: 0.0


jwt:
  secret-key: asdlkd48fgsefn38ovxg5fsdmf0sfmeakn3mdgmdfg5ggr6feskasdflfedfsfpaow0k

stripe:
  api:
    secret: ${STRIPE_API_SECRET}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}


client.url: http://localhost:8080               #front-End url (temporary-localhost)


logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG



minio:
  url: http://localhost:9000          # or minio:9000 if inside docker network
  access-key: minioadmin
  secret-key: minioadmin123
  project-bucket: projects